-- 코드를 입력하세요
SELECT 
MONTH(H.START_DATE) MONTH,
H.CAR_ID,
COUNT(*) RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
JOIN 
    (SELECT
    CRCRH.CAR_ID,
    COUNT(*) CNT
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY CRCRH
    WHERE
        CRCRH.START_DATE >= "2022-08-01" AND CRCRH.START_DATE < "2022-11-01"
    GROUP BY CAR_ID
    HAVING COUNT(*) >= 5) T
    ON T.CAR_ID = H.CAR_ID
WHERE
    H.START_DATE >= "2022-08-01" AND H.START_DATE < "2022-11-01"
GROUP BY CAR_ID, MONTH(H.START_DATE)
ORDER BY MONTH ASC, H.CAR_ID DESC