SELECT 
SALES_DATE,
PRODUCT_ID,
USER_ID,
SALES_AMOUNT
from
(SELECT
SALES_DATE,
PRODUCT_ID,
USER_ID,
SALES_AMOUNT
from ONLINE_SALE os
UNION
SELECT
SALES_DATE,
PRODUCT_ID,
null,
SALES_AMOUNT
from OFFLINE_SALE ofs) a
where SALES_DATE >= "2022-03-01" and SALES_DATE < "2022-04-01"
order by SALES_DATE asc, PRODUCT_ID asc, USER_ID asc;