SELECT
    H.HISTORY_ID,
    ROUND(
        (DATEDIFF(H.END_DATE, H.START_DATE) + 1)
        * C.DAILY_FEE
        * (
            1 - CASE
                WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 90 THEN P90.DISCOUNT_RATE
                WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 30 THEN P30.DISCOUNT_RATE
                WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 7 THEN P7.DISCOUNT_RATE
                ELSE 0
            END / 100
        )
    ) AS FEE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
JOIN CAR_RENTAL_COMPANY_CAR C
    ON H.CAR_ID = C.CAR_ID
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P7
    ON P7.CAR_TYPE = C.CAR_TYPE
    AND P7.DURATION_TYPE = '7일 이상'
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P30
    ON P30.CAR_TYPE = C.CAR_TYPE
    AND P30.DURATION_TYPE = '30일 이상'
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P90
    ON P90.CAR_TYPE = C.CAR_TYPE
    AND P90.DURATION_TYPE = '90일 이상'
WHERE C.CAR_TYPE = '트럭'
ORDER BY FEE DESC, H.HISTORY_ID DESC;