
WITH RECURSIVE 
PRICE_GROUP AS (
    SELECT 0 AS PRICE
    UNION ALL
    
    SELECT PRICE + 10000
    FROM PRICE_GROUP
    WHERE PRICE < (SELECT MAX(PRICE) - 10000 FROM PRODUCT)
)

SELECT PG.PRICE PRICE_GROUP,COUNT(DISTINCT P.PRODUCT_ID) PRODUCTS
FROM PRICE_GROUP PG
    LEFT JOIN PRODUCT P 
    ON P.PRICE >= PG.PRICE AND P.PRICE < PG.PRICE + 10000
GROUP BY PG.PRICE
having COUNT(DISTINCT P.PRODUCT_ID) != 0
