-- 코드를 입력하세요
SELECT 
USB.WRITER_ID USER_ID,
UGU.NICKNAME NICKNAME,
SUM(USB.PRICE) TOTAL_SALES
FROM USED_GOODS_BOARD USB
JOIN USED_GOODS_USER UGU
    ON USB.WRITER_ID = UGU.USER_ID
WHERE USB.STATUS = 'DONE'
GROUP BY USB.WRITER_ID
HAVING SUM(USB.PRICE) >= 700000
ORDER BY TOTAL_SALES