-- 코드를 입력하세요
SELECT
B.CATEGORY,
SUM(BS.SALES) AS TOTAL_SALES
FROM BOOK_SALES BS
JOIN BOOK B ON BS.BOOK_ID = B.BOOK_ID
WHERE BS.SALES_DATE >= "2022-01-01" AND BS.SALES_DATE < "2022-02-01"
GROUP BY B.CATEGORY
ORDER BY B.CATEGORY ASC