-- 코드를 입력하세요
SELECT
FP.CATEGORY,
FP_MAX.MAX_PRICE,
FP.PRODUCT_NAME

FROM FOOD_PRODUCT FP
JOIN (
    SELECT CATEGORY,MAX(PRICE) MAX_PRICE
    FROM FOOD_PRODUCT
    GROUP BY CATEGORY
) FP_MAX
ON FP_MAX.MAX_PRICE = FP.PRICE
AND FP_MAX.CATEGORY = FP.CATEGORY
WHERE FP.CATEGORY IN ('과자', '국', '김치', '식용유')
ORDER BY FP.PRICE desc;