-- 코드를 입력하세요
SELECT
FH.FLAVOR
FROM
FIRST_HALF FH
JOIN (
    SELECT SHIPMENT_ID, FLAVOR, SUM(TOTAL_ORDER) TOTAL_ORDER
    FROM JULY
    GROUP BY FLAVOR
     ) J ON FH.FLAVOR = J.FLAVOR
ORDER BY FH.TOTAL_ORDER + J.TOTAL_ORDER DESC
LIMIT 3