-- 코드를 입력하세요

SELECT RI.FOOD_TYPE,
RI.REST_ID,
RI.REST_NAME,
RI.FAVORITES
FROM REST_INFO RI
JOIN (
    SELECT FOOD_TYPE,MAX(FAVORITES) M
    FROM REST_INFO
    GROUP BY FOOD_TYPE
    ) TMP
    ON TMP.FOOD_TYPE = RI.FOOD_TYPE
    AND TMP.M = RI.FAVORITES
ORDER BY FOOD_TYPE DESC