WITH RECURSIVE HOURS as (
    SELECT 0 AS HOUR
    
    UNION ALL
    
    SELECT HOUR + 1
    FROM HOURS
    WHERE HOUR < 23
)

SELECT H.HOUR, COUNT(AO.DATETIME)
FROM HOURS H
    LEFT JOIN ANIMAL_OUTS AO
        ON HOUR(AO.DATETIME) = H.HOUR
GROUP BY H.HOUR
ORDER BY H.HOUR